name: build-test

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    paths-ignore:
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y libssl-dev pkg-config && \
          wget -O /tmp/cargo-make.zip https://github.com/sagiegurari/cargo-make/releases/download/0.37.15/cargo-make-v0.37.15-x86_64-unknown-linux-gnu.zip && \
          sudo unzip /tmp/cargo-make.zip -d /tmp && \
          sudo mv /tmp/cargo-make-v0.37.15-x86_64-unknown-linux-gnu/cargo-make $HOME/.cargo/bin/cargo-make && \
          sudo chmod +x $HOME/.cargo/bin/cargo-make
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - name: Test
        run: cargo make test --profile development
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy -- -Dwarnings
